name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./Greencell  # Specify your Django app folder

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
        working-directory: ./Greencell  # Specify your Django app folder

      - name: Deploy to Azure
        run: az webapp up --name HelloGCM --resource-group HelloGreencell
        env:
          AZURE_WEBAPP_PACKAGE_PATH: .
        working-directory: ./Greencell  # Specify your Django app folder
